

import { Template } from '@/components/Template/Template'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'TBoard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <Template>{children}</Template>
}
